import type { Metadata } from "next";
import { Oswald , Dancing_Script } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

 
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${dancingScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden ">{children}</body>
    </html>
  );
}
