import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${oswald.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-hidden ">{children}</body>
    </html>
  );
}
